version: "3.9"
services:
  backend:
    container_name: backend
    image: ghcr.io/taletalesarb/simple-web-app-with-login:latest
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - "5000:5000"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
    name: test-network