version: "3.9"
services:
  backend:
    container_name: backend
    image: ghcr.io/taletalesarb/simple-app-with-login:latest
    # #dev
    # build: .
    # volumes:
    #   - .:/user/app/
    # #end-dev
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - "5000:5000"
    networks:
      - test-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

networks:
  test-network:
    driver: bridge
    name: test-network